### ISSUE TITLE
VerifyError: Expecting a stackmap frame at branch target 12

### ISSUE THREAD

**Issue by klapaucius** [rahulmutt/ghcvm#59]
```haskell
lvl1_r7rH = 1
seven1 = 2
s2 = 0

wg1_r7rI ww_s7mE w_s7mA ww1_s7mI =
    case (rem w_s7mA seven1) == s2 of 
      False ->
        case w_s7mA == lvl1_r7rH of 
          False ->
            wg1_r7rI
              (ww_s7mE * ww_s7mE)
              (quot (w_s7mA - lvl1_r7rH) seven1)
              (ww_s7mE * ww1_s7mI)
          True -> ww_s7mE * ww1_s7mI
      True ->
        wg1_r7rI
          (ww_s7mE * ww_s7mE) (quot w_s7mA seven1) ww1_s7mI

wf ww_s7mS w_s7mP =
    case (rem w_s7mP seven1) == s2 of
      False ->
        case w_s7mP == lvl1_r7rH of 
          False ->
            wg1_r7rI
              (ww_s7mS * ww_s7mS)
              (quot (w_s7mP - lvl1_r7rH) seven1)
              ww_s7mS
          True -> ww_s7mS
      True -> wf (ww_s7mS * ww_s7mS) (quot w_s7mP seven1)

main7 = 1000000 :: Int -- 16777216 :: Int 
lvl2_r7rJ = [5, 7 .. ]
main3 = 3 : main4

lvl3_r7rK x_aBf =
    let y_a4LG = x_aBf in
    case (4 <= y_a4LG) of
      False -> True
      True ->
        case rem y_a4LG 2 of
          0 -> False
          _ ->
            let go_a4Mt ds_a4Mu =
                  case ds_a4Mu of
                    [] -> True
                    y1_X4NA : ys_X4NC ->
                      let x1_X4Pu = y1_X4NA in
                      case ((x1_X4Pu * x1_X4Pu) <= y_a4LG) of 
                        False -> True
                        True ->
                          case x1_X4Pu of
                            (-1) -> False
                            -- 0 -> case divZeroError of wild7_00 { }
                            _ -> case rem y_a4LG x1_X4Pu of
					0 -> False
                                	_ -> go_a4Mt ys_X4NC
            in go_a4Mt main3

main4 = filter lvl3_r7rK lvl2_r7rJ
main_primes = 2 : main3

wgo w_s7n5 ww_s7n9 = case w_s7n5 of 
      [] -> ww_s7n9
      y_a4Mz : ys_a4MA ->
        let x_a4LC = y_a4Mz in
        let y1_a4LG = main7 in
        case x_a4LC <= y1_a4LG of 
          False -> ww_s7n9;
          True ->
              let wgo1_X7qh w1_X7oa ww1_X7of = case w1_X7oa of
                    [] -> ww1_X7of
                    y2_X4NH : ys1_X4NJ ->
                      let x1_X4MP = y2_X4NH in
                      case (x1_X4MP <= y1_a4LG) of
                        False -> ww1_X7of
                        True -> wgo1_X7qh ys1_X4NJ (ww1_X7of + 1)
              in wgo1_X7qh ys_a4MA (ww_s7n9 + 1)

main = print $ wgo main_primes 0
```

```bash
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 12
Exception Details:
  Location:
    main/Main$mainzuwgo1zuX7qh.enter(Lghcvm/runtime/stg/StgContext;)V @149: goto
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2b05 b600 184d 2b06 b600 184e 2bb6 001e
    0x0000010: 3605 2c2b b600 222b 1505 b600 252b 04b6
    0x0000020: 0018 3a04 1904 c000 29b6 002b 049f 0073
    0x0000030: 1904 c000 0959 b400 303a 0659 b400 343a
    0x0000040: 0757 2bb6 001e 3609 2bb4 0037 59bb 003d
    0x0000050: 5919 06b2 003f b700 42b6 0045 572b 05b2
    0x0000060: 004b b600 50b2 0053 2bb6 002e 2b15 09b6
    0x0000070: 0025 2b04 b600 183a 0819 08c0 0029 b600
    0x0000080: 2b04 9f00 16bb 000c 592d b700 563a 0a19
    0x0000090: 074d 190a 4ea7 ff77 2d2b b600 2ea7 0008
    0x00000a0: 2d2b b600 2eb1                         
  Stackmap Table:
    full_frame(@152,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer,Object[#28],Object[#28],Object[#28],Integer},{})
    full_frame(@157,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer,Object[#28],Object[#28],Object[#28],Integer},{})
    full_frame(@160,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer},{})
    full_frame(@165,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer},{})

	at main.Main.<clinit>(Unknown Source)
	at ghcvm.main.main(Unknown Source)

```

**Comment by rahulmutt** [comment]
How was the code above generated?

**Comment by klapaucius** [comment]
``` ghc -O2 -ddump-simpl -dsuppress-all -ddump-to-file ```

ghc 8.0.1

from
```haskell
primes = 2:3:filter isPrime [5,7..] :: [Int]
isPrime x = all (/= 0) . map (rem x) . takeWhile ((<= x) . (^2)) $ primes
main = print . length . takeWhile (<= 2^24) $ primes
```
edited, core -> haskell

**Comment by rahulmutt** [comment]
I am unable to reproduce that bug. Instead, I get this exception:
```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Vector$Itr.next(Vector.java:1136)
	at ghcvm.runtime.thunk.UpdateFrame.doRaiseAsync(UpdateFrame.java:28)
	at ghcvm.runtime.stg.Capability.raiseAsync(Capability.java:952)
	at ghcvm.runtime.stg.Capability.throwToSingleThreaded__(Capability.java:870)
	at ghcvm.runtime.stg.Capability.throwToSingleThreaded(Capability.java:854)
	at ghcvm.runtime.stg.Capability.detectDeadlock(Capability.java:493)
	at ghcvm.runtime.stg.Capability.schedule(Capability.java:156)
	at ghcvm.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at ghcvm.runtime.Rts.evalLazyIO(Rts.java:91)
	at ghcvm.runtime.Rts.hsMain(Rts.java:36)
	at ghcvm.main.main(Unknown Source)
```
Can you make sure that you are the most recent commit and do a  `./cleaninstall.sh` and let me know the result?

**Comment by klapaucius** [comment]
```bash
klapaucius@u1604:~/sievej/dist/build/sievej$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
klapaucius@u1604:~/sievej/dist/build/sievej$ java -classpath sievej.jar ghcvm.main
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 12
Exception Details:
  Location:
    main/Main$mainzuwgo1zuX7qh.enter(Lghcvm/runtime/stg/StgContext;)V @149: goto
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2b05 b600 184d 2b06 b600 184e 2bb6 001e
    0x0000010: 3605 2c2b b600 222b 1505 b600 252b 04b6
    0x0000020: 0018 3a04 1904 c000 29b6 002b 049f 0073
    0x0000030: 1904 c000 0959 b400 303a 0659 b400 343a
    0x0000040: 0757 2bb6 001e 3609 2bb4 0037 59bb 003d
    0x0000050: 5919 06b2 003f b700 42b6 0045 572b 05b2
    0x0000060: 004b b600 50b2 0053 2bb6 002e 2b15 09b6
    0x0000070: 0025 2b04 b600 183a 0819 08c0 0029 b600
    0x0000080: 2b04 9f00 16bb 000c 592d b700 563a 0a19
    0x0000090: 074d 190a 4ea7 ff77 2d2b b600 2ea7 0008
    0x00000a0: 2d2b b600 2eb1                         
  Stackmap Table:
    full_frame(@152,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer,Object[#28],Object[#28],Object[#28],Integer},{})
    full_frame(@157,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer,Object[#28],Object[#28],Object[#28],Integer},{})
    full_frame(@160,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer},{})
    full_frame(@165,{Object[#4],Object[#22],Object[#28],Object[#28],Object[#28],Integer},{})

	at main.Main.<clinit>(Unknown Source)
	at ghcvm.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
@klapaucius I have added a patch to codec-jvm that may fix this bytecode error - can you do a ```./cleaninstall.sh``` and let me know if it fixes your problem?
