### ISSUE TITLE
Doubles don't work

### ISSUE THREAD

**Issue by Jyothsnasrinivas** [rahulmutt/ghcvm#68]
```haskell

module Main where

main = do
  print $ min 3.4 3.2

```
```
Exception in thread "main" java.lang.NoSuchMethodError: ghcvm.base.Utils.isDoubleNegativeZero(D)I
	at base.ghc.Float$isDoubleNegativeZZero.enter(Unknown Source)
	at base.ghc.Float$zdLr1MAYzdcisNegativeZZero1.enter(Unknown Source)
	at ghcvm.runtime.apply.StgFun.apply(StgFun.java:116)
	at ghcvm.runtime.apply.ApP.stackEnter(ApP.java:17)
```

**Comment by rahulmutt** [comment]
#70 fixed the NoSuchMethodError, but now we have a new exception at the haskell level:
```
Ix{Int}.index: Index (-1) out of range ((0,324))
```

**Comment by rahulmutt** [comment]
Not able to reproduce on master. Closing.
